backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Headline", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "text" }
